### PR TITLE
Verify mobile using OTP

### PR DESCRIPTION
**Pull request by Dhroov7**
@championswimmer @witty123 Please review. Messaging service is not added yet.
screen shot 2018-09-28 at 5 46 15 pm
screen shot 2018-09-28 at 5 46 26 pm
screen shot 2018-09-28 at 5 56 14 pm

### CODE REVIEW

**Comment by championswimmer** [comment]
looks good till now
will merge when connected to sms service

the hbs logic should be same as email
once verified, show the verified number only do not show the contact no and verified no separately

**Comment by Dhroov7** [comment]
@championswimmer Done with the changes.

**Comment by Dhroov7** [comment]
@championswimmer Sms service code is added.

**Comment by Dhroov7** [comment]
@championswimmer Any updates on this?

**Pull request closed without merging**
