### PR TITLE
[WIP] event

### LINKED ISSUE #347: event subscription frontend + logic for clients
when editing **trusted** clients only (**not** when creating, when creating simply let the current form remain) we need this kind of UI - 

| users  | demographics | addresses | clients |
|--------|--------------|-----------|---------|
| 🔳CREATE | ◽️CREATE       | 🔳CREATE    | ◽️CREATE  |
| 🔳UPDATE | 🔳UPDATE       | ◽️UPDATE    | 🔳UPDATE  |
| 🔳DELETE | 🔳DELETE       | 🔳DELETE    | ◽️DELETE  |

so people can select which events they want their client to listen to via webhook

**do not show the form unless a webhook URL is present**
you can render it as a disabled form if webhookURL is absent, or not render at all. 

When form is submitted to edit a client, respective eventSubscription should be created (or removed, as required).

BOUNTY: 3000

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
fixes #347

### CODE REVIEW

**Comment by championswimmer** [comment]
@VibhorCodecianGupta 

image

# this is not called "work in progress" this is called UTTER FUCKING HORSESHIT. 

I am inclined to disqualify you from BOSS, but I will let this slide, and just be extremely wary of every working together with you on any project in future in my life.

**Comment by championswimmer** [comment]
even this https://github.com/coding-blocks/oneauth/pull/349 is acceptable as [WIP] because there is some progress towards the intended goal that I can see. But [WIP] PRs are to be made when you have put in significant amount of work, done 70-80% of the work, and then need an interim review to understand how to proceed further. 

[WIP] prs are not just to wedge a leg in between the doors so that you can claim a bounty. you just defeated the entire purpose of participating in an open source project.

**Comment by VibhorCodecianGupta** [comment]
@championswimmer I had commits with a whole lotta work already, including the UI of the event table in the parent issue. I apologise if this looks like some cheap tactic to get the first PR for the issue, but it isn't. Apologies once again.

**Comment by championswimmer** [comment]
Oh please explain to me how a PR with a single empty line is supposed to look like to me ? A whole lot of _**work**_ in _progress_ I see?

**Comment by VibhorCodecianGupta** [comment]
Won't repeat. Will submit after completion. Apologies once again.

**Pull request closed without merging**
