### PR TITLE
Added close other sessions feature

### LINKED ISSUE #1045: add feature to "close all other sessions" - this should expire all live tokens for that user

### PR DESCRIPTION
**Pull request by prathambatra**
Signed-off-by: prathambatra <batrapratham999@gmail.com>
fixes #1045 
Screenshot from 2020-07-13 14-42-28
ezgif com-video-to-gif (2)

### CODE REVIEW

**Comment by prathambatra** [comment]
@championswimmer

**Comment by championswimmer** [comment]
This needs to invalidate all existing valid auth tokens too

**Comment by prathambatra** [comment]
> This needs to invalidate all existing valid auth tokens too

okay got it.

**Comment by prathambatra** [comment]
@championswimmer actually I didn't get it completely. how to create an auth token. when I login in, by default there are no auth tokens for the user.

**Comment by championswimmer** [comment]
When you login to another app via oneauth, then auth tokens are created

**Comment by prathambatra** [comment]
Screenshot from 2020-07-20 03-13-14
@championswimmer

**Comment by prathambatra** [comment]
also, review other changes.

**Pull request merged**
