### PR TITLE
excluded social access tokens

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
@championswimmer any updates?

**Comment by championswimmer** [comment]
already fixed

**Comment by championswimmer** [comment]
Actually true. Can you make a fresh PR on current master? (include Google too). Removing the refreshToken as well.

**Comment by championswimmer** [comment]
(I'll award the bounty to both the PRs)

**Comment by VibhorCodecianGupta** [comment]
@championswimmer #186 is the fresh PR :)

**Pull request closed without merging**
