### PR TITLE
change the /clients/me path to /users/me/clients

### LINKED ISSUE #205: change the /clients/me path to /users/me/clients
ideally **my clients** should be on `/users/me/clients` following RESTful convention

### PR DESCRIPTION
**Pull request by architkshk**
fixes #205 @championswimmer Please review.
Changed /clients/me path to /users/me/clients
Changed /clients/me/add path to /users/me/clients/add
Changed /clients/me/:id path to /users/me/clients/:id
Changed /clients/me/:id/edit path to /users/me/clients/:id/edit

Also changed various links on frontend part.

### CODE REVIEW

**Comment by championswimmer** [comment]
there shouldn't be a `clients/all` path. it should simply be `/clients`

**Comment by architkshk** [comment]
@championswimmer Done!!!

**Comment by architkshk** [comment]
@championswimmer Please merge If everything looks fine?

**Comment by championswimmer** [comment]
done already

**Comment by architkshk** [comment]
@championswimmer #206 only Changes /clients/me path to /users/me/clients and not others.i think they need to be changed too.
Please check.

**Comment by championswimmer** [comment]
@architkshk no that was all that was needed others are fine

**Pull request closed without merging**
