### PR TITLE
test

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
@championswimmer this travis config runs perfectly on a locally setup node project. Also, here's how the codecov looks:

screen shot 2018-08-15 at 3 23 06 pm

**Comment by championswimmer** [comment]
Would need adding travis, circle ci and codecov batches to README too. 

Checkout https://shields.io on how to make badges for these services

**Comment by championswimmer** [comment]
Also travis and/or circle ci should upload the the coverage report to codecov. The issue isn't completely done without that.

**Comment by championswimmer** [comment]
@VibhorCodecianGupta 
Ok will consider the ones that were merged before the deadline. 
The ones that were not, I would think would be a slipper slope to go down, because in this day and age, internet outage becomes a bit dubious reason to bend rules for (your issue might be real, but it's hard to explain to others the same).

**Comment by VibhorCodecianGupta** [comment]
@championswimmer Thank you so much. Of course, do proceed as you deem appropriate :)

**Comment by VibhorCodecianGupta** [comment]
@championswimmer Thanks a lot. I'm just requesting for those PRs which were accepted with some minor changes, btw (like #326). Of course, do proceed as you deem appropriate :)

**Pull request merged**
