### PR TITLE
Added the graduation year field in the edit profile page

### PR DESCRIPTION
**Pull request by muskankhedia**
Fixes: #610 

_The changes in the edit profile page are been shown below:_

Screenshot at 2019-06-05 01-41-20

### CODE REVIEW

**Comment by muskankhedia** [comment]
@TdevM pls have a look. The travis is failing because of some error in it and not because of the changes made by me.

**Comment by TdevM** [comment]
You've only added the frontend part here. The form here is supposed to update the graduation year of the user currently logged in. How do you think that's going to happen?

**Comment by muskankhedia** [comment]
> You've only added the frontend part here. The form here is supposed to update the graduation year of the user currently logged in. How do you think that's going to happen?

The data is linked with the `user` models and it has the field of graduation year and it's been updated on clicking on the submit button.

**Comment by championswimmer** [comment]
Are you sure there is a gradYear field on backend already ?

**Comment by muskankhedia** [comment]
> Are you sure there is a gradYear field on backend already ?

Yaa, i have checked it.

**Comment by witty123** [comment]
@muskankhedia this PR was incomplete, please make sure that you test all the functionality before pushing the code. This PR fixed it. 
https://github.com/coding-blocks/oneauth/pull/621

**Pull request merged**
