### PR TITLE
WIP: lint initialization and file fixes

### PR DESCRIPTION
**Pull request by gurrrung**
Commands
1) `npm run lint` => lint the files
2) `npm run lint:fix` => run the formatter

- [x] two spaces
- [x] no semi
- [x] space inside brackets
- [x] single quotes

### CODE REVIEW

**Comment by gurrrung** [comment]
Hey, @championswimmer  actually CodeFactors error are colliding with your requirements. It is asking me to use double quotes instead.

**Comment by championswimmer** [comment]
We can fix that by having an .editorconfig file

**Comment by gurrrung** [comment]
> We can fix that by having a .editorconfig file

I'm not even touching `public_static\js\script.js:54` but CodeFactor is giving error for it looks like linting checks are only happening on PRs. Further, Can you disable it from your side? Because we are doing `npm run lint` in Travis CI. I tried couple of things but seems like it doesn't accept configuration files. https://support.codefactor.io/i18-ignoring-issues-and-patterns

**Comment by gurrrung** [comment]
ping

**Comment by gurrrung** [comment]
should we do this in small PRs?

**Pull request closed without merging**
